### POST auth login
POST http://localhost:3000/api/auth/login
Content-Type: application/json; charset=utf-8

{
    "email": "     TESTMAIL2@mail.com      ",
    "password": "MotDePasse02"
}

### GET user authentication page
GET http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTc3MTg5NTA3NiwiZXhwIjoxNzcxODk1OTc2fQ.H_mRXf-KnosOMDQrqLo-loA9nV7f_ev8oQyECTX4obE

### POST refresh token
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json; charset=utf-8

### POST logout
POST http://localhost:3000/api/auth/logout
Content-Type: application/json; charset=utf-8

