### POST auth login
POST http://localhost:3000/api/auth/login
Content-Type: application/json; charset=utf-8

{
    "email": "     TESTMAIL1@mail.com      ",
    "password": "MotDePasse01"
}

### GET user authentication page
GET http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTc3MTk1ODc3OSwiZXhwIjoxNzcxOTU5Njc5fQ.bMoTGUTbp7f-Rpbbud5Npe_75VyG_qFJXVp8VtHYHCE

### POST refresh token
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json; charset=utf-8

### POST logout
POST http://localhost:3000/api/auth/logout
Content-Type: application/json; charset=utf-8


### POST register
POST http://localhost:3000/api/auth/register
Content-Type: application/json; charset=utf-8

{
    "username": "newUser",
    "email": "         newUser@mail.com",
    "password": "newUserpassword@01"
}