BEGIN;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "username" TEXT UNIQUE NOT NULL,
    "email" TEXT UNIQUE NOT NULL,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;